--------------------------------------------------------
--  File created - Sunday-August-16-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence FEEDBACK
--------------------------------------------------------

   CREATE SEQUENCE  "FEEDBACK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FEEDBACK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FEEDBACK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence QUERY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "QUERY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ASSIGNMENT
--------------------------------------------------------

  CREATE TABLE "ASSIGNMENT" 
   (	"ID" NUMBER(20,0), 
	"QUESTIONS" VARCHAR2(256 BYTE), 
	"MODULE" VARCHAR2(50 BYTE), 
	"TOPIC" VARCHAR2(100 BYTE), 
	"ENDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table CONTACTS_TABLE
--------------------------------------------------------

  CREATE TABLE "CONTACTS_TABLE" 
   (	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"DESIGNATION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table FEEDBACK_TABLE
--------------------------------------------------------

  CREATE TABLE "FEEDBACK_TABLE" 
   (	"ID" NUMBER(5,0), 
	"TRAINER_NAME" VARCHAR2(40 BYTE), 
	"RATING" VARCHAR2(20 BYTE), 
	"FEEDBACK_MESSAGE" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table QUERY_TABLE
--------------------------------------------------------

  CREATE TABLE "QUERY_TABLE" 
   (	"QUERYID" NUMBER(10,0), 
	"QUERYLANG" VARCHAR2(255 BYTE), 
	"QUERYNAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table QUOTE
--------------------------------------------------------

  CREATE TABLE "QUOTE" 
   (	"QUOTE_ID" NUMBER, 
	"QUOTE_DATA" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table SESSION_TABLE
--------------------------------------------------------

  CREATE TABLE "SESSION_TABLE" 
   (	"SESSION_ID" NUMBER(5,0), 
	"SESSION_TITLE" VARCHAR2(50 BYTE), 
	"STARTTIME" VARCHAR2(30 BYTE), 
	"ENDTIME" VARCHAR2(30 BYTE), 
	"BATCH" VARCHAR2(25 BYTE), 
	"VENUE" VARCHAR2(30 BYTE), 
	"TRAINER" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"USERNAME" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"DOB" DATE, 
	"GENDER" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"MOBILE_NO" VARCHAR2(13 BYTE), 
	"ADDRESS" VARCHAR2(40 BYTE), 
	"DATE_OF_JOINING" DATE, 
	"PASSCODE" VARCHAR2(20 BYTE), 
	"DESIGNATION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
REM INSERTING into ASSIGNMENT
SET DEFINE OFF;
Insert into ASSIGNMENT (ID,QUESTIONS,MODULE,TOPIC,ENDDATE) values (101,'1. What is Servlet ?
2. Explain about lifecycle of Servlet ?','Advance JAVA ','Introduction To Servlet',to_date('02-JUL-20','DD-MON-RR'));
REM INSERTING into CONTACTS_TABLE
SET DEFINE OFF;
Insert into CONTACTS_TABLE (NAME,EMAIL,DESIGNATION) values ('Kush Saini','kush.saini@hcl.com','TSS SCHOLAR');
Insert into CONTACTS_TABLE (NAME,EMAIL,DESIGNATION) values ('Gaurav Kumar','gaurav-kuma@hcl.com','TRAINER HCLTSS');
Insert into CONTACTS_TABLE (NAME,EMAIL,DESIGNATION) values ('Dia','dia@hcl.com','TSS SCHOLAR');
Insert into CONTACTS_TABLE (NAME,EMAIL,DESIGNATION) values ('null','null','null');
REM INSERTING into FEEDBACK_TABLE
SET DEFINE OFF;
Insert into FEEDBACK_TABLE (ID,TRAINER_NAME,RATING,FEEDBACK_MESSAGE) values (1,'Hema','Excellent','She is an amazing Trainer........:)');
Insert into FEEDBACK_TABLE (ID,TRAINER_NAME,RATING,FEEDBACK_MESSAGE) values (21,'Hema','Excellent','AMazing');
REM INSERTING into QUERY_TABLE
SET DEFINE OFF;
Insert into QUERY_TABLE (QUERYID,QUERYLANG,QUERYNAME) values (1,'Jenkins','What is Jenkins ?');
Insert into QUERY_TABLE (QUERYID,QUERYLANG,QUERYNAME) values (22,'Jira','What are the Advantages of using JIRA ?');
REM INSERTING into QUOTE
SET DEFINE OFF;
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (0,'Your limitation are only your imagination:)');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (1,'Push yourself because no one else is going to do it for you!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (2,'Sometimes later becomes never.Do it now!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (3,'Great things never come from comfort zones!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (4,'Dream it. Wish it. Do it.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (5,'Success doesnnott just find you. You have to go out and get it!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (6,'The harder you work for something, the greater you will feel when you achieve it!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (7,'Dream bigger. Do bigger.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (8,'Do not stop when you are tired. Stop when you are done.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (9,'Wake up with determination. Go to bed with satisfaction.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (10,'Do something today that your future self will thank you for.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (11,'Little things make big days!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (12,'It is going to be hard, but hard does not mean impossible.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (13,'Donot wait for opportunity. Create it.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (14,'Sometimes we are tested, not to show our weaknesses, but to discover our strengths.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (15,'The key to success is to focus on goals, not obstacles.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (16,'Dream it. Believe it. Build it.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (17,'A day wasted on others is not wasted on one self.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (18,'Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.!!');
Insert into QUOTE (QUOTE_ID,QUOTE_DATA) values (19,'You can influence, direct and control your own environment. You can make your life what you want it to be.!!');
REM INSERTING into SESSION_TABLE
SET DEFINE OFF;
Insert into SESSION_TABLE (SESSION_ID,SESSION_TITLE,STARTTIME,ENDTIME,BATCH,VENUE,TRAINER) values (101,'JAVA Advance(IO)','29-06-2020 (12 PM)','29-06-2020 (3 PM)','JAVA','WFH','Mr. Gaurav Kumar');
Insert into SESSION_TABLE (SESSION_ID,SESSION_TITLE,STARTTIME,ENDTIME,BATCH,VENUE,TRAINER) values (102,'Maven (java)','30-06-2020 (2 PM)','30-06-2020 (4 PM)','JAVA','SNU','Mr. Vipin Gupta');
Insert into SESSION_TABLE (SESSION_ID,SESSION_TITLE,STARTTIME,ENDTIME,BATCH,VENUE,TRAINER) values (501,'JIRA','3:00 PM ','4:00 PM','SNU','JIRA-001','Mr.Rohan');
REM INSERTING into USERS
SET DEFINE OFF;
Insert into USERS (USERNAME,PASSWORD,NAME,DOB,GENDER,EMAIL,MOBILE_NO,ADDRESS,DATE_OF_JOINING,PASSCODE,DESIGNATION) values ('ks226','kush1234','Kush Saini',to_date('21-FEB-01','DD-MON-RR'),'Male','ks@hcl.com','9045353271','Defence Colony Roorkee-247667',to_date('03-JUL-19','DD-MON-RR'),'admin$','SCHOLAR');
Insert into USERS (USERNAME,PASSWORD,NAME,DOB,GENDER,EMAIL,MOBILE_NO,ADDRESS,DATE_OF_JOINING,PASSCODE,DESIGNATION) values ('admin','admin$1234','Super User',to_date('01-FEB-01','DD-MON-RR'),'Male','Mylearnzia@gmail.com','0000','Delhi',to_date('01-FEB-01','DD-MON-RR'),'admin@1234','ADMIN');
Insert into USERS (USERNAME,PASSWORD,NAME,DOB,GENDER,EMAIL,MOBILE_NO,ADDRESS,DATE_OF_JOINING,PASSCODE,DESIGNATION) values ('di810','dia@1234','Dia',to_date('22-OCT-99','DD-MON-RR'),'Female','di810@snu.edu.in','9045353271','Village Mandoli , New Delhi',to_date('03-JUL-19','DD-MON-RR'),null,'Scholar');
--------------------------------------------------------
--  DDL for Index CONTACTS_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTACTS_TABLE_PK" ON "CONTACTS_TABLE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index FEEDBACK_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FEEDBACK_TABLE_PK" ON "FEEDBACK_TABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index SESSION_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESSION_TABLE_PK" ON "SESSION_TABLE" ("SESSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index SYS_C007367
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007367" ON "ASSIGNMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index SYS_C007386
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007386" ON "QUERY_TABLE" ("QUERYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERS_PK" ON "USERS" ("USERNAME", "PASSWORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index SYS_C007367
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007367" ON "ASSIGNMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index CONTACTS_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTACTS_TABLE_PK" ON "CONTACTS_TABLE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index FEEDBACK_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FEEDBACK_TABLE_PK" ON "FEEDBACK_TABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index SYS_C007386
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007386" ON "QUERY_TABLE" ("QUERYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index SESSION_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESSION_TABLE_PK" ON "SESSION_TABLE" ("SESSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERS_PK" ON "USERS" ("USERNAME", "PASSWORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  Constraints for Table ASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "ASSIGNMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACTS_TABLE
--------------------------------------------------------

  ALTER TABLE "CONTACTS_TABLE" ADD CONSTRAINT "CONTACTS_TABLE_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "CONTACTS_TABLE" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FEEDBACK_TABLE
--------------------------------------------------------

  ALTER TABLE "FEEDBACK_TABLE" ADD CONSTRAINT "FEEDBACK_TABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "FEEDBACK_TABLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUERY_TABLE
--------------------------------------------------------

  ALTER TABLE "QUERY_TABLE" ADD PRIMARY KEY ("QUERYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "QUERY_TABLE" MODIFY ("QUERYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUOTE
--------------------------------------------------------

  ALTER TABLE "QUOTE" ADD CONSTRAINT "QUOTE_ID" PRIMARY KEY ("QUOTE_ID", "QUOTE_DATA") DISABLE;
--------------------------------------------------------
--  Constraints for Table SESSION_TABLE
--------------------------------------------------------

  ALTER TABLE "SESSION_TABLE" ADD CONSTRAINT "SESSION_TABLE_PK" PRIMARY KEY ("SESSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "SESSION_TABLE" MODIFY ("SESSION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERNAME", "PASSWORD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
  ALTER TABLE "USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
